### ISSUE TITLE
Configuring V-In current limit

### ISSUE THREAD

**Issue by pubudeux** [mini-box/ups#2]
Hey, I am using the NUC-UPS in an application where I am powering a server from a weak/unpredictable power source. 

I have a power supply that maxes out at ~12v 2.2A and then is disabled until a power cycle if that is exceeded. I'm trying to find a way to limit the maximum current draw of the V-In on the ups, but not sure if there is a software-based configuration.

For example, I have another power supply that gets to ~12v 1.3A and then runs in CC mode and drops voltage, but the 12v 1.3A rating is too low for this application, as it causes the server to run on battery far too often. Is the NUC-UPS capable of setting a current limit for the input source?

**Comment by ashibod** [comment]
For startup, you can set the VIN_MIN_STARTUP and VIN_MIN_RUNNING parameters. 
Unfortunately you can't limit the current input using the provided software.
As You mentioned, if with the Vin active it switches to battery, i think 1.3A is not enough and this causes a drop in voltage and the unit switches to battery input.  
You need to use a Vin source which can deliver more amps to the NUC-UPS.
