### ISSUE TITLE
openups only retrieves 3 out of 6 cells

### ISSUE THREAD

**Issue by davidwkerr** [mini-box/ups#6]
Given everything I do is Linux based, I am pleased to have this tool. However, I recently upgraded three OpenUPS installations from AGM batteries  to use 6 LFP cells each. The Windows configurator shows the 6 cells correctly but Linux openups only shows 3 of them. Other provided information looks accurate:

openups -t openups -s
openups version 1.0. Device selected: openups
Selected device openups: Open UPS
interface 0 already claimed by driver "usbfs", attempting to detach it
usb_detach_kernel_driver_np returned 0
Product: OPEN-UPS, Manufacturer: Mini-Box.Com, Firmware Version: PBSO4-LiFePO
VIN: 24.283251
 VBat: 20.576571
 VOut: 12.623610 
 CCharge: 0.000000
Temperature: 60.000000
 VCell1: 3.410860
 VCell2: 3.428000
 VCell3: 3.428000
CDischarge: 0.000000
 VerMajor: 1
 VerMinor: 9
State: 2
 Capacity: 0
RTE: 0

**Comment by davidwkerr** [comment]
...I did also try it after shutting down NUT and all related processes. No change.

**Comment by lorenzoooooo** [comment]
Hi, I had the same problem. Actualy the system acquires them but doesn't print the values. You just have to go in the routine of your device (in src/lib) and modify the printValues() method of your object to print every cell voltage. 
Here is  a capture of the printValues() method. In my case I am using an openups:
<img width="817" alt="Immagine 2022-10-18 125248" src="https://user-images.githubusercontent.com/62096402/196410756-2c96d0c0-c24e-4dde-87a7-97a04d7775d8.png">

**Comment by davidwkerr** [comment]
Thank you so much!
I'll do this.
Regards,
David
